service:
  name: panopticon

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/** # exclude puppeteer chrome if exists

provider:
  name: aws
  runtime: nodejs8.10

functions:
  daily:
    handler: handler.daily
    events:
      - http:
          method: get
          path: daily
      - schedule: rate(1 day)

layers:
  chrome:
    path: layer
