service:
  name: panopticon

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-chrome
  - serverless-offline

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - node_modules/@serverless-chrome/lambda/dist/headless-chromium
    - node_modules/phantomjs-prebuilt
    - layer/**

provider:
  name: aws
  runtime: nodejs8.10

functions:
  daily:
    handler: handler.daily
    events:
      - http:
          method: get
          path: daily
      - schedule: rate(1 day)
    layers:
      - { Ref: ChromeLambdaLayer }

layers:
  chrome:
    package:
      artifact: layer.zip
